### ISSUE TITLE
The magnitude of loss

### ISSUE THREAD

**Issue by Debrove** [winycg/CIRKD#17]
Hi! Thanks for your great work!

I integrated your code in my project and I used PSP-101 as teacher to distill PSP-18. I found the magnitude of memory_pixel_contrast_loss and memory_region_contrast_loss is small, which is from 0.002 to 0.0003 when the lambda is set to 0.1. So I'm curious about the magnitude of loss. 

It's appreciated if you could share your any training logs or any other suggestions to help me. Thank you very much!

**Comment by Debrove** [comment]
BTW, I just applied memory_pixel_contrast_loss and memory_region_contrast_loss on baseline. The mIoU only increased 0.13.

**Comment by winycg** [comment]
Hi, thanks for your attention！I think you can manually tune the lambda to control the magnitude since the contribution of **memory_pixel_contrast_loss ** and **memory_region_contrast_loss ** may be changed over various architecture pairs. An example of training logs is shown in
[deeplab_mobile_resnet101_mobilenetv2_log.txt](https://1drv.ms/t/s!AuC2iKyBWkCZgrMrdneis-QLGGi9NQ?e=r5Gk8r).
